export const LANDING = 'Landing'
export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const ABOUT = 'About'
export const NEW_PROJECT_FORM = 'New Project Form'
export const PROJECT_VIEW = 'Project View'
